# Generated by Django 3.0.3 on 2020-02-20 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishes')),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.RemoveField(
            model_name='list',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
        migrations.AddField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ListItems',
        ),
        migrations.AddField(
            model_name='wish',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wishapp.List'),
        ),
    ]
