# Generated by Django 3.0.3 on 2020-02-20 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0003_auto_20200220_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
