# Generated by Django 3.0.3 on 2020-02-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0007_auto_20200220_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='item_logo'),
        ),
    ]
